# Generated by Django 4.0.3 on 2022-04-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_guardian_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian_info',
            name='Class',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='guardian_info',
            name='Subject',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='guardian_info',
            name='Teacher',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
