# Generated by Django 4.0.3 on 2022-04-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_guardian_info_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian_info',
            name='Class',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
