# Generated by Django 4.0.3 on 2022-04-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_guardian_info_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guardian_info',
            new_name='guardian_inf',
        ),
    ]
