# Generated by Django 4.0.3 on 2022-04-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_guardian_info_guardian_inf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian_inf',
            name='Class',
        ),
    ]
