# Generated by Django 4.0.3 on 2022-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_guardian_info_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian_info',
            name='Class',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
