# Generated by Django 4.0.3 on 2022-04-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_guardian_info_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian_info',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='guardian_info',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='guardian_info',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='guardian_info',
            name='Education',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
